# @Author: Your name
# @Date:   2025-12-09 20:53:30
# @Last Modified by:   JogFeelingVI
# @Last Modified time: 2026-01-01 08:52:38
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.7.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-12-09T12:51:55Z"
  labels:
    app: beautifultorvalds-pod
  name: beautifultorvalds-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    - name: PYTHONDONTWRITEBYTECODE
      value: 1
    - name: SSH_PASS
      value: "lxy929123"
    image: localhost/vscode-dev-env
    name: vscode-dev-env
    command: ["/bin/sh", "-c"]
    args: [echo "root:$(SSH_PASS)" | chpasswd && /usr/sbin/sshd -D]
    ports:
    - containerPort: 22
      hostPort: 2222
    - containerPort: 56789
      hostPort: 56789
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /codex
      name: home-feelingvi-github-flet-podman-dex-codex-host-0
  volumes:
  - hostPath:
      path: /home/feelingvi/Github/flet_podman_dex/codex
      type: Directory
    name: home-feelingvi-github-flet-podman-dex-codex-host-0
